### ISSUE TITLE
GXMods not working even on normal windows

### ISSUE THREAD

**Issue by BluOcean00** [noblereign/GX-Mods-Extension#11]
**Describe the issue**

Whenever I open the GX Store the GXM button does not appear anywhere. This happens when I'm using normal windows even.

**To Reproduce**
1. Go to '...' I go to Gx Store just like the guide says
2. Click on '....' Whenever I click in any theme the button of GXM does not appear
3. Watch it all crumble

**Expected behavior**
What did you expect to happen?

The GXM Button allowing me to download

**Screenshots**

![imagen](https://github.com/noblereign/GX-Mods-Extension/assets/164665598/2cf91ba3-2241-4a0b-848c-afed99c8fd86) 

Is the button supposed to appear here?

**System Information**
 - OS: [e.g. Windows, Mac, Linux] Windows
 - Browser [e.g. Firefox] Firefox
 - Version [e.g. 120] 124.0.1 (64-bit)

**Additional context**

**Comment by noblereign** [comment]
yep that's where the buttons supposed to be, and I immediately see the issue thanks to the screenshot
... I forgot to handle languages other than English. 😭😭😭
for context the extension looks for a button saying "Try with Opera GX" to replace, since your language isn't English there is no button on the page it can find, causing it to never appear. 
ROOKIE MISTAKE I KNOW, I'll fix it once I get back home. Really sorry for the inconvenience, for now you can work around it by setting the language to English. 😓

**Comment by BluOcean00** [comment]
Omg it worked instantly!! TYSM, specially for being so quick to answer you are a God send

**Comment by noblereign** [comment]
Resolved with 22a01de (4.2.0) 🐺
