### ISSUE TITLE
Make extension for Chromium-based browsers

### ISSUE THREAD

**Issue by KjalaNIX** [noblereign/GX-Mods-Extension#27]
**Describe your cool new feature!**

A description of what you want to see added! If it's related to a problem, be sure to write that down too.
I am currently using Vivaldi GX  CSS Mod and this extension would complete my 'gamey' configuration. In short, I am proposing even if it's a CRX on Github for a chromium version of this extension.

**Additional context**

![Uploading VGX.png…]()

**Comment by noblereign** [comment]
there *is* a chromium version of 4.0.0 at https://github.com/noblereign/GX-Mods-Extension/tree/chrome-polyfill but it's extremely scuffed.
i did also make a chromium version of 6.3.1 for that exact same use case of using it with Vivaldi GX, but i never really shared it around anywhere. guess i might as well share it now.
a few caveats though:
1. i made this with the intent of getting it to play sounds, i didn't care about preserving all the functionality. some stuff is literally impossible to port over to Chromium browsers (themes), and some functionality can be straight up broken (address bar detection, unfocused muting...)
2. absolutely none of the CSS is tuned for Chromium browsers, so everything looks weird
3. i did not bother porting it to Manifest v3, so it'll probably stop working eventually unless you disable automatic updates

i don't plan on making or maintaining an official chromium version, due to GXM using manifest v2 -- even if i did maintain a chromium manifest v2 version, Firefox's implementation of MV2 is completely different from Chromium's, enough that porting isn't as simple as "drag and drop with a polyfill" anymore :/
same deal with the rendering engine differences completely ruining the look of the extension...

anyway, here's scuffed 6.3.1 for Chromium. go wild, but don't report any bugs while using it: https://arctic.wolfdo.gg/bowl/cc0572fb-a2b7-4f96-b0a7-31fb723679f2

**Comment by noblereign** [comment]
oh i just remembered too:
i could not get mod installation to work in chromium for some reason, it might have worked for 4.0.0 but it doesn't work in the 6.3.1 port 💀
i literally just made a local mod for my music...
![image](https://github.com/user-attachments/assets/07a8a852-bbff-4337-b48e-627bac240004)
i *did* literally throw the port together in like an hour but jeez 😭
