### ISSUE TITLE
Sound for keyboard in address bar cannot be enabled

### ISSUE THREAD

**Issue by RaflIsLife** [noblereign/GX-Mods-Extension#29]
(Android) Even after enabling proxy option and search suggestions. But I can't find search permission setting for the extension

![IMG-20240908-WA0000](https://github.com/user-attachments/assets/5cfacdf9-50e7-412b-a8bb-fcfe5de21b7a)

After clicking it, nothing happens

**Comment by noblereign** [comment]
yeah that usually pops up a permission request on PC, seems like it doesn't work on android because the menu takes up the whole screen instead of being a pop-up
when i get around to updating i'll check if having this setting enabled works at all on android.
if it does i'll probably just grant the proxy permission on install for android, but if it doesn't i'll disable this setting for android

**Comment by noblereign** [comment]
okay so unfortunately after further investigation, firefox for android doesn't implement the "search" api at all, which is something that feature needs to work. it straight up didn't make a single sound when i tried it, so i guess i have to disable that toggle for android :(

i will definitely revisit this if firefox for android implements the search api
